version: "3.5"

volumes:
  orderer.blockchain.sensefinity.com:
  peer0.org1.blockchain.sensefinity.com:
  peer0.org2.blockchain.sensefinity.com:
  explorerdb.blockchain.sensefinity.com:
  explorer.blockchain.sensefinity.com:

networks:
  test:
  tools_proxy:
    external:
      name: tools_network

services:

  ca_org1:
    image: hyperledger/fabric-ca:1.4.2
    environment:
      FABRIC_CA_HOME: /etc/hyperledger/fabric-ca-server
      FABRIC_CA_SERVER_CA_NAME: ca-org1
      FABRIC_CA_SERVER_TLS_ENABLED: "true"
      FABRIC_CA_SERVER_PORT: 7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
    container_name: ca_org1
    networks:
      - tools_proxy
      - test

  ca_org2:
    image: hyperledger/fabric-ca:1.4.2
    environment:
      FABRIC_CA_HOME: /etc/hyperledger/fabric-ca-server
      FABRIC_CA_SERVER_CA_NAME: ca-org2
      FABRIC_CA_SERVER_TLS_ENABLED: "true"
      FABRIC_CA_SERVER_PORT: 8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/org2:/etc/hyperledger/fabric-ca-server
    container_name: ca_org2
    networks:
      - tools_proxy
      - test
    
  ca_orderer:
    image: hyperledger/fabric-ca:1.4.2
    environment:
      FABRIC_CA_HOME: /etc/hyperledger/fabric-ca-server
      FABRIC_CA_SERVER_CA_NAME: ca-orderer
      FABRIC_CA_SERVER_TLS_ENABLED: "true"
      FABRIC_CA_SERVER_PORT: 9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - tools_proxy
      - test

  orderer.blockchain.sensefinity.com:
    container_name: orderer.blockchain.sensefinity.com
    image: hyperledger/fabric-orderer:2.2.1
    environment:
      ORDERER_GENERAL_LOGLEVEL: info
      FABRIC_LOGGING_SPEC: INFO
      ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
      ORDERER_GENERAL_LISTENPORT: "7050"
      ORDERER_GENERAL_GENESISMETHOD: file
      ORDERER_GENERAL_GENESISFILE: /var/hyperledger/orderer/genesis.block
      ORDERER_GENERAL_LOCALMSPID: OrdererMSP
      ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/orderer/msp
      ORDERER_GENERAL_TLS_ENABLED: "true"
      ORDERER_GENERAL_TLS_PRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_GENERAL_TLS_CERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_GENERAL_TLS_ROOTCAS: "[/var/hyperledger/orderer/tls/ca.crt]"
      ORDERER_KAFKA_VERBOSE: "true"
      ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_GENERAL_CLUSTER_ROOTCAS: "[/var/hyperledger/orderer/tls/ca.crt]"
      ORDERER_METRICS_PROVIDER: prometheus
      ORDERER_OPERATIONS_LISTENADDRESS: 0.0.0.0:8443
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - "7050:7050"
      - "8443:8443"
    networks:
      - tools_proxy
      - test
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./organizations/ordererOrganizations/blockchain.sensefinity.com/orderers/orderer.blockchain.sensefinity.com/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/blockchain.sensefinity.com/orderers/orderer.blockchain.sensefinity.com/tls:/var/hyperledger/orderer/tls
      - orderer.blockchain.sensefinity.com:/var/hyperledger/production/orderer

  couchdb0:
    container_name: couchdb0
    image: couchdb:3.1.1
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: adminpw
    ports:
      - "5984:5984"
    networks:
      - test

  couchdb1:
    container_name: couchdb1
    image: couchdb:3.1.1
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: adminpw
    ports:
      - "6984:5984"
    networks:
      - tools_proxy
      - test

  peer0.org1.blockchain.sensefinity.com:
    container_name: peer0.org1.blockchain.sensefinity.com

    image: hyperledger/fabric-peer:2.2.1
    environment:
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
      CORE_LOGGING_LEVEL: INFO
      CORE_PEER_GOSSIP_USELEADERELECTION: "true"
      CORE_PEER_GOSSIP_ORGLEADER: "false"
      CORE_PEER_GOSSIP_SKIPHANDSHAKE: "true"

      FABRIC_LOGGING_SPEC: DEBUG
      ORDERER_GENERAL_LOGLEVEL: DEBUG
      CORE_PEER_LOCALMSPID: Org1MSP

      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: hyperledger_test

      CORE_PEER_ID: peer0.org1.blockchain.sensefinity.com
      CORE_PEER_ADDRESS: peer0.org1.blockchain.sensefinity.com:7051
      CORE_PEER_LISTENADDRESS: 0.0.0.0:7051
      CORE_PEER_CHAINCODEADDRESS: peer0.org1.blockchain.sensefinity.com:7052
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_BOOTSTRAP: peer0.org1.blockchain.sensefinity.com:9051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer0.org1.blockchain.sensefinity.com:7051

      # CORE_OPERATIONS_LISTENADDRESS: 0.0.0.0:9440

      CORE_LEDGER_STATE_STATEDATABASE: CouchDB
      CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: couchdb0:5984
      CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: admin
      CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: adminpw
      CORE_METRICS_PROVIDER: prometheus
      CORE_PEER_TLS_ENABLED: "true"
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/crypto/peer/tls/server.crt
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/crypto/peer/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/crypto/peer/tls/ca.crt
      CORE_PEER_MSPCONFIGPATH: /etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb0
    ports:
      - "7051:7051"
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - ./organizations/peerOrganizations/org1.blockchain.sensefinity.com/peers/peer0.org1.blockchain.sensefinity.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./organizations/peerOrganizations/org1.blockchain.sensefinity.com/peers/peer0.org1.blockchain.sensefinity.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - peer0.org1.blockchain.sensefinity.com:/var/hyperledger/production
    networks:
      - tools_proxy
      - test

  peer0.org2.blockchain.sensefinity.com:
    container_name: peer0.org2.blockchain.sensefinity.com

    image: hyperledger/fabric-peer:2.2.1
    environment:
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
      CORE_LOGGING_LEVEL: INFO
      CORE_PEER_GOSSIP_USELEADERELECTION: "true"
      CORE_PEER_GOSSIP_ORGLEADER: "false"
      CORE_PEER_GOSSIP_SKIPHANDSHAKE: "true"

      FABRIC_LOGGING_SPEC: DEBUG
      ORDERER_GENERAL_LOGLEVEL: debug
      CORE_PEER_LOCALMSPID: Org2MSP

      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: hyperledger_test

      CORE_PEER_ID: peer0.org2.blockchain.sensefinity.com
      CORE_PEER_ADDRESS: peer0.org2.blockchain.sensefinity.com:9051
      CORE_PEER_LISTENADDRESS: 0.0.0.0:9051
      CORE_PEER_CHAINCODEADDRESS: peer0.org2.blockchain.sensefinity.com:9052
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:9052
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer0.org2.blockchain.sensefinity.com:9051
      CORE_PEER_GOSSIP_BOOTSTRAP: peer0.org2.blockchain.sensefinity.com:9051

      CORE_LEDGER_STATE_STATEDATABASE: CouchDB
      CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: couchdb1:5984
      CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: admin
      CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: adminpw
      CORE_METRICS_PROVIDER: prometheus

      # CORE_OPERATIONS_LISTENADDRESS: 0.0.0.0:9440

      CORE_PEER_TLS_ENABLED: "true"
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/crypto/peer/tls/server.crt
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/crypto/peer/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/crypto/peer/tls/ca.crt
      CORE_PEER_MSPCONFIGPATH: /etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb1
    ports:
      - "9051:9051"
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - ./organizations/peerOrganizations/org2.blockchain.sensefinity.com/peers/peer0.org2.blockchain.sensefinity.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./organizations/peerOrganizations/org2.blockchain.sensefinity.com/peers/peer0.org2.blockchain.sensefinity.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - peer0.org2.blockchain.sensefinity.com:/var/hyperledger/production
    networks:
      - tools_proxy
      - test

  explorerdb.blockchain.sensefinity.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.blockchain.sensefinity.com
    hostname: explorerdb.blockchain.sensefinity.com
    environment:
      DATABASE_DATABASE: fabricexplorer
      DATABASE_USERNAME: hppoc
      DATABASE_PASSWORD: password
    volumes:
      - explorerdb.blockchain.sensefinity.com:/var/lib/postgresql/data
    networks:
      - tools_proxy
      - test

  explorer.blockchain.sensefinity.com:
    image: hyperledger/explorer:latest
    container_name: explorer.blockchain.sensefinity.com
    hostname: explorer.blockchain.sensefinity.com
    environment:
      DATABASE_HOST: explorerdb.blockchain.sensefinity.com
      DATABASE_DATABASE: fabricexplorer
      DATABASE_USERNAME: hppoc
      DATABASE_PASSWD: password
      LOG_LEVEL_APP: debug
      LOG_LEVEL_DB: debug
      LOG_LEVEL_CONSOLE: info
      LOG_CONSOLE_STDOUT: "true"
      DISCOVERY_AS_LOCALHOST: "false"
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection.json:/opt/explorer/app/platform/fabric/connection.json
      - ./organizations:/tmp/crypto
      - explorer.blockchain.sensefinity.com:/opt/wallet
    depends_on:
      - peer0.org1.blockchain.sensefinity.com
      - ca_org1
      - explorerdb.blockchain.sensefinity.com
    ports:
      - 8080:8080
    networks:
      - tools_proxy
      - test
